### ISSUE TITLE
Error in stage [play.sockjs.core.streams.CancellationSuppresser@37e0822a]: Cannot push port (SubSourceOutlet(CancellationSuppresserSubSource)) twice, or before it being pulled

### ISSUE THREAD

**Issue by ProChirathF** [fdimuccio/play2-sockjs#34]
I am seeing this error intermittently in logs, it seems to be happening at close(). I use actor pattern for sockjs websocket handling

`akka.event.slf4j.Slf4jLogger$$anonfun$receive$1 $anonfun$applyOrElse$1 
Error in stage [play.sockjs.core.streams.CancellationSuppresser@37e0822a]: Cannot push port (SubSourceOutlet(CancellationSuppresserSubSource)) twice, or before it being pulled
java.lang.IllegalArgumentException: Cannot push port (SubSourceOutlet(CancellationSuppresserSubSource)) twice, or before it being pulled
	at akka.stream.stage.GraphStageLogic$SubSourceOutlet.push(GraphStage.scala:1508)
	at play.sockjs.core.streams.CancellationSuppresser$$anon$1$$anon$4.onPush(CancellationSuppresser.scala:48)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:523)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:409)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:606)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:485)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:739)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:765)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:614)
	at akka.actor.ActorCell.invoke(ActorCell.scala:583)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by ProChirathF** [comment]
Issue is seen when the play server is force terminated(kill 9)
